In [3]:
import seaborn as sns
import numpy as np
import glob
import matplotlib.pyplot as plt
import pprint
import matplotlib.pyplot as plt
from itertools import combinations
from  pathlib import Path
from readerscf import parse_sdr_file
from get_project_root import get_project_root
from replace_outliers import replace_outliers
from calculate_inverse_matrix import calculate_inverse_matrix
from detrend import detrend_dataframe,detrend_preserve_mean_level,detrend_and_shift_positive,detrend_preserve_baseline,detrend_full
from substractdf import subtract_column_min,subtract_percentile_norm
from multiply_matrix_with_dataframe import multiply_matrix_with_dataframe,matrix_multiply_with_dataframe
from subtract_mean_from_first_n import subtract_mean_from_first_n
from remove_baseline import remove_baseline
from config import IUPAC, ref_str, color_map
from deconvolve_nnls import deconvolve_nnls
from center_dataframe import center_dataframe
from estimate_M_from_data import estimate_M_from_data
from evaluate_quality import evaluate_quality
from estimate_crosstalk_matrix import estimate_crosstalk_matrix
from estimate_M_yin import estimate_M_yin
from estimate_M_correlation import estimate_M_correlation,estimate_M_correlation_crostalk
from deconvolve_domnisoru import deconvolve_domnisoru
from multiply_matrix_with_dataframe import multiply_matrix_with_dataframe
from estimate_M_goodpeaks_crostalk import estimate_M_goodpeaks_crostalk
from estimate_M_clusters_crostalk import estimate_M_clusters_crostalk
from estimate_M_from_clean_peaks import estimate_M_from_clean_peaks
from estimate_M_sklearn import estimate_M_sklearn
from  divide_matrices import  divide_matrices
from compare_matrices import compare_matrices
from replace_outliers import replace_outliers
from normalize_diagonal import normalize_diagonal
from divide_matrices_np import divide_matrices_np
from tqdm import tqdm 

def main():
    project_root = get_project_root()
    project_root = Path(get_project_root())
    print(f"📁 Корень проекта: {project_root}")
    


    # 🔹 Точный путь к папке с файлами
    srd_dir = project_root / "files" / "сырые SRD" / "сырые SRD" 

    if not srd_dir.is_dir():
        print(f"❌ Папка не найдена: {srd_dir}")
        return

    srd_files = sorted(srd_dir.glob("*.srd"))
    if not srd_files:
        print("⚠️ Файлы .srd не найдены в папке tqmd.")
        return

    print(f"📂 Найдено файлов: {len(srd_files)}\n")
    # 🔹 Цикл с прогресс-баром
    with tqdm(srd_files, desc="🔄 Обработка SRD", unit="файл") as pbar:
        for srd_path in pbar:
            # Отображаем текущий файл справа в строке прогресса
            pbar.set_postfix(file=srd_path.name[:20] + "..." if len(srd_path.name) > 18 else srd_path.name)
            
            try:
                sdr_matrix, sdr_channels, sdr_meta = parse_sdr_file(srd_path)
                
                matrix = sdr_matrix.to_numpy()
                if matrix.shape[0] < 10 or matrix.shape[1] < 4:
                    tqdm.write(f"   ⚠️ Матрица слишком мала в {srd_path.name}, пропуск.")
                    continue
                    
                matrixdef = matrix[6:10, 0:4]
                tqdm.write(f"   matrixdef:\n{matrixdef}")
                tqdm.write(f"   matrix inv:\n{np.linalg.inv(matrixdef)}")

                data0 = sdr_channels.loc[:, ['dR110', 'dR6G', 'dTAMRA', 'dROX']]
                data0.columns = ['G', 'A', 'T', 'C']
                
                data0 = subtract_column_min(data0)
                data0 = center_dataframe(data0, method='percentile', percentile=2)
                
                matrix1 = estimate_M_from_data(
                    raw=data0,
                    dye_order=['G', 'A', 'T', 'C'],
                    min_purity=0.8,
                    peak_height=400,
                    peak_distance=20,
                    peak_prominence=150
                )
                tqdm.write(f"   matrix1:\n{matrix1}")
                matrix2 = estimate_crosstalk_matrix(data0, init_M=matrixdef)
                tqdm.write(f"   matrix2:\n{matrix2}")
                
                matrix1def = divide_matrices_np(matrix1, matrixdef)
                tqdm.write(f"   matrix1def:\n{matrix1def}")
                matrix2def = divide_matrices_np(matrix2, matrixdef)
                tqdm.write(f"   matrix2def:\n{matrix2def}")

                tqdm.write(f"   ✅ {srd_path.name} готов")
                
            except Exception as e:
                tqdm.write(f"   ❌ Ошибка в {srd_path.name}: {e}")
    
if __name__ == "__main__":
    main()

📁 Корень проекта: C:\Users\Admin\Documents\GitHub\dnasegnercrosstalk
📂 Найдено файлов: 40



🔄 Обработка SRD:   2%|▊                                | 1/40 [00:00<00:12,  3.06файл/s, file=3_pGEM_A3_PDMA6_50.s...]

   matrixdef:
[[1.         0.45442271 0.05485368 0.00475959]
 [0.73666734 1.         0.39780498 0.01566364]
 [0.43882051 0.62656242 1.         0.25624526]
 [0.20345469 0.31454486 0.56733644 1.        ]]
   matrix inv:
[[ 1.51032801 -0.84882143  0.29411056 -0.06925735]
 [-1.1277791   1.97319603 -0.82913169  0.1869214 ]
 [ 0.03709389 -0.87648276  1.5667097  -0.38790957]
 [ 0.02640909  0.04929865 -0.68789057  1.1753708 ]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.26980728  0.10088707  0.        ]
 [ 0.          1.15631692 -0.16151205  0.        ]
 [ 0.         -0.39614561  1.22521667  0.        ]
 [ 0.         -0.02997859 -0.16459169  1.        ]]
Найдено пиков: 592
  Итерация 1: max Δ = 0.625512
  Итерация 2: max Δ = 0.026133
  Итерация 3: max Δ = 0.010547
  Сходимость на итерации 5
   matrix2:
[[ 0.36

🔄 Обработка SRD:   5%|█▋                               | 2/40 [00:01<00:20,  1.88файл/s, file=3_pGEM_B3_PDMA6_50.s...]

   matrixdef:
[[1.         0.43628675 0.05150481 0.00714676]
 [0.7464748  1.         0.38239858 0.02149237]
 [0.4566119  0.6320703  1.         0.29575685]
 [0.22059479 0.33302453 0.55968916 1.        ]]
   matrix inv:
[[ 1.48598492 -0.7931545   0.26743835 -0.07266993]
 [-1.11648009  1.91864401 -0.78800983  0.19980231]
 [ 0.01696632 -0.85482712  1.57680796 -0.44810075]
 [ 0.03451886  0.01444771 -0.67909123  1.20028867]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Найдено пиков: 871
  Итерация 1: max Δ = 0.619864
  Итерация 2: max Δ = 0.010523
  Итерация 3: max Δ

🔄 Обработка SRD:   8%|██▍                              | 3/40 [00:02<00:28,  1.32файл/s, file=3_pGEM_C3_PDMA6_50.s...]

   matrixdef:
[[1.         0.42949274 0.05087501 0.00714976]
 [0.78511477 1.         0.37884179 0.02154703]
 [0.48368555 0.64682263 1.         0.26829728]
 [0.22363143 0.32498074 0.55633968 1.        ]]
   matrix inv:
[[ 1.5152341  -0.79890597  0.26097615 -0.06363869]
 [-1.20463924  1.96551012 -0.78116109  0.17584536]
 [ 0.03781485 -0.89507906  1.55934493 -0.39935208]
 [ 0.03159268  0.03787556 -0.67202562  1.17926066]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Найдено пиков: 848
  Итерация 1: max Δ = 0.652676
  Итерация 2: max Δ = 0.024194
  Итерация 3: max Δ

🔄 Обработка SRD:  10%|███▎                             | 4/40 [00:02<00:25,  1.42файл/s, file=3_pGEM_D3_PDMA6_50.s...]

   matrixdef:
[[1.         0.40438506 0.04796062 0.00704807]
 [0.77651501 1.         0.37622795 0.0220618 ]
 [0.47049898 0.63607621 1.         0.26384562]
 [0.21569785 0.3188563  0.55418664 1.        ]]
   matrix inv:
[[ 1.46308871 -0.72156772  0.23213923 -0.05564179]
 [-1.14982498  1.88694675 -0.74515243  0.16307981]
 [ 0.0345837  -0.87032172  1.54053091 -0.38750522]
 [ 0.03187802  0.03629642 -0.66621704  1.17475301]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Найдено пиков: 827
  Итерация 1: max Δ = 0.643399
  Итерация 2: max Δ = 0.027136
  Итерация 3: max Δ

🔄 Обработка SRD:  12%|████▏                            | 5/40 [00:03<00:24,  1.43файл/s, file=3_pGEM_E3_PDMA6_50.s...]

   matrixdef:
[[1.         0.41252762 0.04856525 0.00584242]
 [0.77566963 1.         0.3788099  0.02060425]
 [0.4643451  0.62281096 1.         0.289561  ]
 [0.22231543 0.32387394 0.56533045 1.        ]]
   matrix inv:
[[ 1.47458035 -0.74013789  0.2451354  -0.06434678]
 [-1.15377148  1.89305868 -0.76866484  0.19031112]
 [ 0.0246199  -0.84353513  1.56474441 -0.43585239]
 [ 0.03193617  0.02830779 -0.69014453  1.1990691 ]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.          0.05929919  0.        ]
 [ 0.          1.         -0.21832884  0.        ]
 [ 0.          0.          1.19946092  0.        ]
 [ 0.          0.         -0.04043127  1.        ]]
Найдено пиков: 851
  Итерация 1: max Δ = 0.641555
  Итера

🔄 Обработка SRD:  15%|████▉                            | 6/40 [00:04<00:29,  1.14файл/s, file=3_pGEM_F3_PDMA6_50.s...]

   matrixdef:
[[1.         0.42935839 0.05054627 0.00621837]
 [0.80652195 1.         0.35937738 0.01978084]
 [0.48212492 0.63509047 1.         0.27355406]
 [0.22681122 0.32467484 0.56256402 1.        ]]
   matrix inv:
[[ 1.53762066 -0.79400341  0.24130382 -0.05986508]
 [-1.25839025  1.95064848 -0.73289358  0.16972568]
 [ 0.04905157 -0.86518997  1.53525743 -0.40316673]
 [ 0.0322234   0.03348713 -0.68045889  1.18527951]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Найдено пиков: 861
  Итерация 1: max Δ = 0.662047
  Итерация 2: max Δ = 0.017483
  Итерация 3: max Δ

🔄 Обработка SRD:  18%|█████▊                           | 7/40 [00:05<00:27,  1.22файл/s, file=4_pGEM_1_A2_PDMA6_50...]

   matrixdef:
[[1.         0.4292562  0.05138054 0.00599975]
 [0.78870344 1.         0.38171935 0.01885023]
 [0.47457409 0.62096852 1.         0.27495438]
 [0.24216056 0.33214748 0.58505702 1.        ]]
   matrix inv:
[[ 1.51589818 -0.79219695  0.26347771 -0.06660626]
 [-1.20492407  1.94587638 -0.79085931  0.18799926]
 [ 0.02348481 -0.84302284  1.56277009 -0.41394021]
 [ 0.01938179  0.03873735 -0.7154316   1.19586456]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Найдено пиков: 854
  Итерация 1: max Δ = 0.685315
  Итерация 2: max Δ = 113.981869
  Итерация 3: max

   matrixdef:
[[1.         0.4698877  0.09678798 0.00711856]
 [0.73191738 1.         0.44920525 0.01894639]
 [0.45704332 0.65647846 1.         0.26384586]
 [0.22151285 0.34263197 0.57146072 1.        ]]
   matrix inv:
[[ 1.53141564 -0.88580374  0.29005842 -0.07064941]
 [-1.13980444  2.08522416 -0.95196965  0.21977954]
 [ 0.04097527 -0.97420482  1.67596942 -0.42403161]
 [ 0.02788943  0.03847225 -0.69582713  1.18266367]]
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.


🔄 Обработка SRD:  20%|██████▌                          | 8/40 [00:06<00:27,  1.16файл/s, file=4_pGEM_1_B2_PDMA6_50...]

   matrix1:
[[ 1.8668313   2.31650526  0.         -0.00420802]
 [ 0.15106304  2.60402535  0.         -0.00705013]
 [-0.84107573 -1.82713505  1.          0.2037001 ]
 [-0.17681862 -2.09339556  0.          0.80755804]]
Найдено пиков: 917
  Итерация 1: max Δ = 0.622944
  Итерация 2: max Δ = 0.023618
  Итерация 3: max Δ = 0.006271
  Сходимость на итерации 5
   matrix2:
[[0.36465479 0.20238494 0.05195989 0.03140689]
 [0.28495351 0.38164114 0.16439665 0.03610344]
 [0.16781824 0.26424964 0.47559638 0.21395612]
 [0.18257347 0.15172427 0.30804708 0.71853356]]
   matrix1def:
[[ 1.8668313   4.92991249  0.         -0.59113289]
 [ 0.20639357  2.60402535  0.         -0.37210951]
 [-1.84025385 -2.78323685  1.          0.77204207]
 [-0.79823186 -6.10974972  0.          0.80755804]]
   matrix2def:
[[0.36465479 0.43070917 0.53684242 4.41197045]
 [0.38932469 0.38164114 0.36597225 1.9055573 ]
 [0.36718234 0.40252599 0.47559638 0.81091329]
 [0.82421162 0.44281996 0.53905205 0.71853356]]
   ✅ 4_pGEM_1_A2_PD

🔄 Обработка SRD:  22%|███████▍                         | 9/40 [00:07<00:29,  1.07файл/s, file=4_pGEM_2_D2_PDMA6_50...]

   matrixdef:
[[1.         0.44790953 0.09635615 0.00737624]
 [0.73395252 1.         0.46988818 0.01833493]
 [0.46322513 0.66742539 1.         0.22984467]
 [0.21574256 0.33505517 0.56862241 1.        ]]
   matrix inv:
[[ 1.49832994 -0.84134183  0.28583307 -0.0613233 ]
 [-1.12379914  2.09774333 -0.98959844  0.19728135]
 [ 0.0503179  -1.0244133   1.6864528  -0.3692108 ]
 [ 0.02466929  0.06115784 -0.68905114  1.15707144]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.          0.         -0.42487047]
 [ 0.          1.          0.          0.11658031]
 [ 0.          0.          1.          0.21243523]
 [ 0.          0.          0.          1.09585492]]
Найдено пиков: 897
  Итерация 1: max Δ = 0.625446
  Итера

🔄 Обработка SRD:  25%|████████                        | 10/40 [00:08<00:29,  1.01файл/s, file=4_pGEM_3_E2_PDMA6_50...]

   matrixdef:
[[1.         0.4309817  0.09379533 0.00601743]
 [0.7543844  1.         0.4691413  0.0184943 ]
 [0.45805666 0.63966322 1.         0.24478064]
 [0.21340694 0.3221207  0.56549299 1.        ]]
   matrix inv:
[[ 1.4887995  -0.79249236  0.26570583 -0.0593418 ]
 [-1.14395863  2.04679055 -0.96964209  0.20637936]
 [ 0.04336876 -0.95900882  1.66666315 -0.39049166]
 [ 0.02624788  0.05212253 -0.68684801  1.16700518]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.28665213  0.          1.68181818  0.        ]
 [ 0.33794412  1.         -4.04545455  0.        ]
 [-0.24441214  0.          6.72727273  0.        ]
 [-0.38018411  0.         -3.36363636  1.        ]]
Найдено пиков: 829
  Итерация 1: max Δ = 0.640571
  Итерация 2: max Δ = 0.013495
  Итерация 3: max Δ = 0.001808
  Итерация 6: max Δ = 0.000000
  Сходимость на

🔄 Обработка SRD:  28%|████████▊                       | 11/40 [00:09<00:27,  1.04файл/s, file=4_pGEM_3_F2_PDMA6_50...]

   matrixdef:
[[1.         0.45672014 0.10021713 0.00638644]
 [0.75464129 1.         0.47264811 0.01877143]
 [0.44557053 0.62925589 1.         0.25993058]
 [0.20562601 0.31450778 0.55302238 1.        ]]
   matrix inv:
[[ 1.53564305 -0.86374511  0.29291224 -0.0697304 ]
 [-1.18515035  2.0982178  -0.99894642  0.22783906]
 [ 0.05455994 -0.94609084  1.67248726 -0.41731955]
 [ 0.02679799  0.04091204 -0.67097684  1.17346828]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 3.64166667  0.          0.          0.        ]
 [-1.175       1.          0.          0.        ]
 [-1.475       0.          1.          0.        ]
 [ 0.00833333  0.          0.          1.        ]]
Найдено пиков: 916
  Итерация 1: max Δ = 0.674494
  Итера

🔄 Обработка SRD:  30%|█████████▌                      | 12/40 [00:10<00:25,  1.11файл/s, file=4_pGEM_4_G2_PDMA6_50...]

   matrixdef:
[[1.         0.43533701 0.08528075 0.00582115]
 [0.74581498 1.         0.44373718 0.0162133 ]
 [0.4662582  0.66056949 1.         0.24336885]
 [0.21015695 0.3227106  0.54530567 1.        ]]
   matrix inv:
[[ 1.48830535 -0.8011119   0.26081355 -0.05914888]
 [-1.13119508  2.03154242 -0.91161156  0.1955047 ]
 [ 0.0467863  -0.97991567  1.63995964 -0.38349977]
 [ 0.02675811  0.04711252 -0.65490435  1.15846371]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 3.11688312  0.          0.1800554   0.00560482]
 [-0.52597403  1.         -0.1634349   0.00576811]
 [-0.57792208  0.          1.12742382  0.18747911]
 [-1.01298701  0.         -0.14404432  0.80114796]]
Найдено пиков: 899
  Итерация 1: max Δ = 1.239420
  Итерация 2: max Δ = 0.606176
  Итерация 3: max Δ = 0.726393
  Итерация 6: max Δ = 0.420075
  Итерация 11: max Δ = 0.139723
  Итерация 16: max Δ = 0.331296
  Итерация 21: max Δ = 0.332829
  Итерация 26: max Δ

🔄 Обработка SRD:  32%|██████████▍                     | 13/40 [00:10<00:22,  1.19файл/s, file=4_pGEM_4_H2_PDMA6_50...]

   matrixdef:
[[1.         0.43546033 0.09335286 0.00630344]
 [0.75393111 1.         0.48261571 0.01821623]
 [0.45244381 0.63680655 1.         0.22891816]
 [0.21186949 0.3242723  0.57691753 1.        ]]
   matrix inv:
[[ 1.4977454  -0.81683354  0.2894926  -0.06083143]
 [-1.15440603  2.08289521 -1.01364866  0.20137682]
 [ 0.05119731 -0.96992497  1.67445464 -0.36596743]
 [ 0.02747872  0.0572036  -0.69865869  1.15872042]]
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 0.80227596  0.14906832  0.         -0.00354935]
 [ 0.18918919  0.93167702  0.          0.00509443]
 [ 0.05263158 -0.11490683  1.          0.19387532]
 [-0.04409673  0.03416149  0.          0.8045796 ]]
Найдено пиков: 907
  Итерация 1: max Δ = 0.678577
  Итерация 2: max Δ = 0.047659
  Итерация 3: max Δ = 0.006750
  Сходимость на итерации 5
   matrix2:
[[0.28924041 0.18485022 0.03464905 0.0349053 ]
 [0.33668411 0.39403208 0.17138819 0.05070455]
 [0.22477487 0

🔄 Обработка SRD:  32%|██████████▍                     | 13/40 [00:11<00:22,  1.19файл/s, file=4_pGEM_4_H2_PDMA6_50...]

   matrixdef:
[[1.         0.42689255 0.09611301 0.00618648]
 [0.78545046 1.         0.50231487 0.02115701]
 [0.48907727 0.64966577 1.         0.2355673 ]
 [0.21093845 0.30496892 0.53123921 1.        ]]
   matrix inv:
[[ 1.51133424 -0.82137454  0.30069469 -0.06280585]
 [-1.20678299  2.15017368 -1.07889126  0.216126  ]
 [ 0.03800476 -1.00761894  1.70460813 -0.38046685]
 [ 0.02904319  0.05281001 -0.63995445  1.14945536]]
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 8.62905085  0.69332734  0.         -0.03114409]
 [-1.20096849  0.97392986  0.         -0.02340377]
 [-2.63592452 -0.24421763  1.          0.18986035]
 [-3.79215783 -0.42303957  0.          0.86468752]]
Найдено пиков: 919
  Итерация 1: max Δ = 0.672987
  Итерация 2: max Δ = 0.699692
  Итерация 3: max Δ = 0.938290
  Сходимость на итерации 5
   matrix2:
[[ 2.32537313  0.2590438   0.33208361  0.02473569]
 [ 0.04477612  0.40713108  0.28314661  0.03619169]
 [-1.1

🔄 Обработка SRD:  35%|███████████▏                    | 14/40 [00:11<00:22,  1.14файл/s, file=5_pGEM1_GenSeq_D4_PD...]

   matrix2def:
[[ 2.32537313  0.60681264  3.45513689  3.99834593]
 [ 0.05700693  0.40713108  0.56368353  1.71062401]
 [-2.44139306  0.32813582  0.16005748  0.83254855]
 [-0.83493265  0.39560264  0.42299643  0.74295141]]
   ✅ 4_pGEM_4_H2_PDMA6_50.srd готов


🔄 Обработка SRD:  38%|████████████                    | 15/40 [00:12<00:18,  1.37файл/s, file=5_pGEM1_GenSeq_E4_PD...]

   matrixdef:
[[1.         0.4493767  0.04777574 0.00553213]
 [0.75812811 1.         0.39136419 0.02123402]
 [0.45746905 0.62164533 1.         0.30263963]
 [0.2239489  0.33055469 0.57398009 1.        ]]
   matrix inv:
[[ 1.51978202 -0.84576523  0.30608013 -0.08308061]
 [-1.15865309  1.9717219  -0.84226246  0.21944424]
 [ 0.01465836 -0.84579627  1.59756347 -0.46560746]
 [ 0.0342311   0.02311648 -0.70710213  1.2133169 ]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.          0.         -0.00320188]
 [ 0.          1.          0.         -0.00656901]
 [ 0.          0.          1.          0.20657265]
 [ 0.          0.          0.          0.80319824]]
Найдено пиков: 609
  Итерация 1: max Δ = 0.596555
  Итера

🔄 Обработка SRD:  40%|████████████▊                   | 16/40 [00:12<00:15,  1.54файл/s, file=5_pGEM1_GenSeq_F4_PD...]

   matrixdef:
[[1.         0.4223772  0.0418312  0.00566559]
 [0.77240247 1.         0.35396385 0.01762198]
 [0.44552344 0.6070134  1.         0.31802389]
 [0.22150896 0.32673404 0.58059007 1.        ]]
   matrix inv:
[[ 1.48942147 -0.75550934  0.24809732 -0.07402575]
 [-1.16232262  1.86811973 -0.73260514  0.2066512 ]
 [ 0.03203461 -0.80514729  1.56436807 -0.48349962]
 [ 0.03125118  0.02443431 -0.72384531  1.22959246]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.05367557  0.          0.33267913  0.        ]
 [ 0.20718848  1.         -0.23265252  0.        ]
 [-0.22356881  0.          0.84991019  0.        ]
 [-0.03729523  0.          0.0500632   1.        ]]
Найдено пиков: 594
  Итерация 1: max Δ = 0.614183
  Итерация 2: max Δ = 0.009317
  Итерация 3: max Δ = 0.003307
  Сходимость на итерации 4
   matrix2:
[[0.378

🔄 Обработка SRD:  42%|█████████████▌                  | 17/40 [00:12<00:12,  1.77файл/s, file=5_pGEM2_GenSeq_G4_PD...]

   matrixdef:
[[1.         0.42427725 0.04200807 0.0041063 ]
 [0.76395476 1.         0.37278795 0.01508858]
 [0.4573907  0.62760025 1.         0.28125143]
 [0.21785687 0.32474038 0.57003689 1.        ]]
   matrix inv:
[[ 1.48515471 -0.77443307  0.2657289  -0.06915003]
 [-1.14693895  1.90953058 -0.77402449  0.19359307]
 [ 0.03187929 -0.85419869  1.55991469 -0.4259705 ]
 [ 0.03073387  0.03553864 -0.69574277  1.19501622]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.          0.         -0.58633094]
 [ 0.          1.          0.         -0.05395683]
 [ 0.          0.          1.          0.38669065]
 [ 0.          0.          0.          1.25359712]]
Найдено пиков: 596
  Итерация 1: max Δ = 0.615074
  Итера

🔄 Обработка SRD:  45%|██████████████▍                 | 18/40 [00:13<00:10,  2.11файл/s, file=5_pGEM2_GenSeq_H4_PD...]

   matrixdef:
[[1.         0.44491437 0.04089687 0.00383   ]
 [0.75310647 1.         0.39532316 0.01819572]
 [0.46847749 0.63754642 1.         0.25837943]
 [0.23005319 0.34065807 0.59528917 1.        ]]
   matrix inv:
[[ 1.50658834 -0.84739704  0.31628508 -0.07207279]
 [-1.14002842  1.98511357 -0.84996892  0.18786022]
 [ 0.01208624 -0.87954051  1.58086224 -0.3925047 ]
 [ 0.03456962  0.04228237 -0.72428379  1.18623827]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.         -0.23921492 -0.01980037]
 [ 0.          1.         -0.02597364  0.02346443]
 [ 0.          0.          1.08583944  0.0600148 ]
 [ 0.          0.          0.17934912  0.93632114]]
Найдено пиков: 590
  Итерация 1: max Δ = 0.622560
  Итерация 2: max Δ = 0.010099
  Итерация 3: max Δ = 0.005806
  Итерация 6: max Δ = 0.001333
  Сходимость на

🔄 Обработка SRD:  48%|███████████████▏                | 19/40 [00:13<00:10,  2.05файл/s, file=6_pGEM_1_A3_PDMA6_36...]

   matrixdef:
[[1.         0.4180482  0.03797491 0.00584571]
 [0.81519836 1.         0.39538619 0.01690114]
 [0.50352681 0.63695103 1.         0.28582451]
 [0.23941998 0.33106777 0.55977279 1.        ]]
   matrix inv:
[[ 1.52044386 -0.8032428   0.30622308 -0.08283842]
 [-1.2470815   2.00067101 -0.86765468  0.22147343]
 [ 0.01760093 -0.87562129  1.59203401 -0.44034623]
 [ 0.03899133  0.02010366 -0.67724074  1.1930043 ]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Найдено пиков: 596
  Итерация 1: max Δ = 0.640007
  Итерация 2: max Δ = 0.011226
  Итерация 3: max Δ

🔄 Обработка SRD:  50%|████████████████                | 20/40 [00:14<00:10,  1.90файл/s, file=6_pGEM_1_B3_PDMA6_36...]

   matrixdef:
[[1.         0.46667361 0.0346798  0.00578643]
 [0.75631028 1.         0.3157022  0.0167726 ]
 [0.46676087 0.63320446 1.         0.31321162]
 [0.23095331 0.3417677  0.57956791 1.        ]]
   matrix inv:
[[ 1.5471402  -0.86236517  0.26317516 -0.07691782]
 [-1.17356331  1.90795048 -0.66835957  0.18412742]
 [ 0.00886052 -0.81095915  1.52462135 -0.4639785 ]
 [ 0.03863362  0.01709614 -0.71597907  1.22374267]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 0.81848185  0.          0.          0.        ]
 [ 0.16006601  1.          0.          0.        ]
 [ 0.1039604   0.          1.          0.        ]
 [-0.08250825  0.          0.          1.        ]]
Найдено пиков: 581
  Итерация 1: max Δ = 0.664261
  Итера

🔄 Обработка SRD:  52%|████████████████▊               | 21/40 [00:15<00:10,  1.77файл/s, file=6_pGEM_2_C3_PDMA6_36...]

   matrixdef:
[[1.         0.48108447 0.0398226  0.00624476]
 [0.74942845 1.         0.32195652 0.01769592]
 [0.45901567 0.62965029 1.         0.31635562]
 [0.22406526 0.33818707 0.57388055 1.        ]]
   matrix inv:
[[ 1.56561752 -0.89779477  0.2727074  -0.08016211]
 [-1.17701892  1.93297669 -0.68428225  0.18962092]
 [ 0.00918673 -0.80864219  1.52948033 -0.46960739]
 [ 0.04198     0.01152092 -0.70742786  1.22333275]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Найдено пиков: 595
  Итерация 1: max Δ = 0.619358
  Итерация 2: max Δ = 0.011654
  Итерация 3: max Δ

🔄 Обработка SRD:  55%|█████████████████▌              | 22/40 [00:15<00:08,  2.04файл/s, file=6_pGEM_2_D3_PDMA6_36...]

   matrixdef:
[[1.         0.49912173 0.04403071 0.00552844]
 [0.78859675 1.         0.3302784  0.01754531]
 [0.44531316 0.58487672 1.         0.31949079]
 [0.22716972 0.32787353 0.59231758 1.        ]]
   matrix inv:
[[ 1.65241789 -0.97150488  0.30024259 -0.08801468]
 [-1.30899338  2.01211868 -0.72808121  0.20454869]
 [ 0.0154992  -0.74492249  1.52654128 -0.47473167]
 [ 0.04462451  0.00220673 -0.73368471  1.23412009]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.          0.14882943  0.        ]
 [ 0.          1.          0.04013378  0.        ]
 [ 0.          0.          0.81438127  0.        ]
 [ 0.          0.         -0.00334448  1.        ]]
Найдено пиков: 586
  Итерация 1: max Δ = 0.615424
  Итера

🔄 Обработка SRD:  57%|██████████████████▍             | 23/40 [00:15<00:08,  2.12файл/s, file=6_pGEM_3_E3_PDMA6_36...]

   matrixdef:
[[1.         0.4636732  0.03647561 0.00576943]
 [0.73977464 1.         0.33083141 0.01778808]
 [0.44276744 0.61345029 1.         0.32494515]
 [0.21177068 0.32480893 0.56672645 1.        ]]
   matrix inv:
[[ 1.5231067  -0.84562683  0.27046683 -0.08163226]
 [-1.12907092  1.88545057 -0.69531253  0.19891397]
 [ 0.0047678  -0.78618485  1.5346185  -0.48470963]
 [ 0.04148093  0.01221954 -0.70114212  1.22737605]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.          0.10332103  0.        ]
 [ 0.          1.          0.20479705  0.        ]
 [ 0.          0.          0.82472325  0.        ]
 [ 0.          0.         -0.13284133  1.        ]]
Найдено пиков: 593
  Итерация 1: max Δ = 0.600783
  Итера

🔄 Обработка SRD:  60%|███████████████████▏            | 24/40 [00:16<00:06,  2.36файл/s, file=6_pGEM_3_F3_PDMA6_36...]

   matrixdef:
[[1.         0.42727277 0.03372255 0.00585804]
 [0.77413726 1.         0.32190621 0.01813308]
 [0.44942293 0.60022151 1.         0.33751738]
 [0.21607389 0.31464455 0.55753559 1.        ]]
   matrix inv:
[[ 1.49653783 -0.75685911  0.23454233 -0.07420471]
 [-1.16370248  1.83145407 -0.65974858  0.19628372]
 [ 0.01411457 -0.76350264  1.52450586 -0.50078525]
 [ 0.03492052  0.01296035 -0.69305846  1.2334797 ]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.         -0.18571429  0.        ]
 [ 0.          1.         -0.38095238  0.        ]
 [ 0.          0.          2.70952381  0.        ]
 [ 0.          0.         -1.14285714  1.        ]]
Найдено пиков: 590
  Итерация 1: max Δ = 0.628238
  Итера

🔄 Обработка SRD:  62%|████████████████████            | 25/40 [00:16<00:06,  2.32файл/s, file=6_pGEM_4_G3_PDMA6_36...]

   matrixdef:
[[1.         0.48026031 0.04148074 0.00592947]
 [0.77232599 1.         0.33137175 0.01690293]
 [0.43168291 0.58199704 1.         0.3153033 ]
 [0.22106448 0.32419795 0.59567529 1.        ]]
   matrix inv:
[[ 1.59373637 -0.90294647  0.28274374 -0.0833376 ]
 [-1.2385748   1.94439737 -0.71134162  0.19876643]
 [ 0.02134661 -0.74617155  1.52544348 -0.46849144]
 [ 0.03650926  0.01371571 -0.74055809  1.23305209]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.         -0.05288462 -0.24259513]
 [ 0.          1.          0.44871795  0.24372427]
 [ 0.          0.          0.9375     -0.64369308]
 [ 0.          0.         -0.33333333  1.64256394]]
Найдено пиков: 590
  Итерация 1: max Δ = 0.605893
  Итерация 2: max Δ = 0.022913
  Итерация 3: max Δ = 0.003033
  Сходимость на итерации 4
   matrix2:
[[0.391

🔄 Обработка SRD:  65%|████████████████████▊           | 26/40 [00:16<00:05,  2.58файл/s, file=6_pGEM_4_H3_PDMA6_36...]

   matrixdef:
[[1.         0.43434986 0.03445055 0.00546129]
 [0.76699305 1.         0.32376361 0.01572732]
 [0.44426724 0.59355384 1.         0.32427743]
 [0.2213196  0.32618663 0.57733494 1.        ]]
   matrix inv:
[[ 1.50032805 -0.77022432  0.24043359 -0.07404735]
 [-1.15275705  1.83245929 -0.66508076  0.19314654]
 [ 0.00420888 -0.74672756  1.51928716 -0.4809495 ]
 [ 0.041532    0.00385394 -0.71340978  1.23105526]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.         -0.29016787  0.          0.13019892]
 [ 0.          1.07673861  0.          0.13019892]
 [ 0.          0.          1.         -0.1880651 ]
 [ 0.          0.21342926  0.          0.92766727]]
Найдено пиков: 592
  Итерация 1: max Δ = 0.748996
  Итерация 2: max Δ = 0.062081
  Итерация 3: max Δ = 0.007725
  Сходимость на итерации 4
   matrix2:
[[0.240

🔄 Обработка SRD:  68%|█████████████████████▌          | 27/40 [00:17<00:07,  1.83файл/s, file=7_pGEM_1_A4_PDMA6_36...]

   matrixdef:
[[1.         0.50267768 0.04023019 0.0048553 ]
 [0.785716   1.         0.32238632 0.0139354 ]
 [0.46662426 0.61304086 1.         0.30208382]
 [0.23653042 0.34180108 0.59484607 1.        ]]
   matrix inv:
[[ 1.65578739 -0.9888959   0.30327521 -0.08587321]
 [-1.30616312  2.03002832 -0.71784233  0.1949011 ]
 [ 0.01407455 -0.78519474  1.51906815 -0.44801224]
 [ 0.04643168  0.00710811 -0.72998625  1.22019254]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.         -0.10178117  0.18203969]
 [ 0.          1.          0.          0.07322127]
 [ 0.          0.          1.42493639 -0.10615279]
 [ 0.          0.         -0.32315522  0.85089184]]
Найдено пиков: 584
  Итерация 1: max Δ = 0.633581
  Итерация 2: max Δ = 0.012135
  Итерация 3: max Δ = 0.003654
  Сходимость на итерации 5
   matrix2:
[[0.352

🔄 Обработка SRD:  70%|██████████████████████▍         | 28/40 [00:18<00:05,  2.11файл/s, file=7_pGEM_1_B4_PDMA6_36...]

   matrixdef:
[[1.         0.48261437 0.03671672 0.00572053]
 [0.81125867 1.         0.37902847 0.01944715]
 [0.52456737 0.6610027  1.         0.29879999]
 [0.24318603 0.33773127 0.57706398 1.        ]]
   matrix inv:
[[ 1.64553226 -1.01243474  0.38352293 -0.104321  ]
 [-1.33870585  2.16682727 -0.9089695   0.23711957]
 [ 0.00745829 -0.9136261   1.61410253 -0.46456906]
 [ 0.04764847  0.04162536 -0.71772042  1.21337279]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 3.91480135  0.         -1.66203414 -0.7896823 ]
 [-2.42823451  1.         -0.7387773   0.02439173]
 [ 0.89858769  0.          3.4715613  -0.31709251]
 [-1.38515453  0.         -0.07074987  2.08238307]]
Найдено пиков: 595
  Итерация 1: max Δ = 0.632443
  Итерация 2: max Δ = 0.016307
  Итерация 3: max Δ = 0.003132
  Итерация 6: max Δ = 0.000000
  Сходимость на итерации 6
   matrix2:
[[0.35651327 0.19490734 0.02084944 0.03941338]
 [0.27852871 0.38145626 0.1729

🔄 Обработка SRD:  72%|███████████████████████▏        | 29/40 [00:18<00:04,  2.21файл/s, file=7_pGEM_2_C4_PDMA6_36...]

   matrixdef:
[[1.         0.45825279 0.04069088 0.00148052]
 [0.80250466 1.         0.3499383  0.01556216]
 [0.49846545 0.64093822 1.         0.31722942]
 [0.24851739 0.36917377 0.61014068 1.        ]]
   matrix inv:
[[ 1.58286226 -0.88418106  0.29516592 -0.08221901]
 [-1.27241859  2.00422783 -0.78331314  0.21918371]
 [ 0.00286596 -0.84176561  1.59522183 -0.49295585]
 [ 0.07462612 -0.00657852 -0.75748494  1.2402884 ]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 6.06246581  0.          0.01703881 -0.61558653]
 [-0.96949767  1.          0.14644826  0.5896706 ]
 [ 0.20612864  0.          0.8581938   0.05360642]
 [-4.29909679  0.         -0.02168087  0.97230951]]
Найдено пиков: 595
  Итерация 1: max Δ = 0.603928
  Итерация 2: max Δ = 0.041096
  Итерация 3: max Δ = 0.021683
  Итерация 6: max Δ = 10.447575
  Сходимость на итерации 8
   matrix2:
[[ 1.60639244e+01  2.61910170e-01  1.11016936e-01  7.19131118e-02]
 [-3.3073

🔄 Обработка SRD:  75%|████████████████████████        | 30/40 [00:18<00:04,  2.35файл/s, file=7_pGEM_2_D4_PDMA6_36...]

   matrixdef:
[[1.         0.43411124 0.03630399 0.00360515]
 [0.78776336 1.         0.3610273  0.02108579]
 [0.50322002 0.65169454 1.         0.28340042]
 [0.23794626 0.34067193 0.59967494 1.        ]]
   matrix inv:
[[ 1.52090972 -0.82078817  0.28193586 -0.06807689]
 [-1.20069419  1.96408853 -0.77496392  0.18253943]
 [ 0.00454411 -0.88268195  1.57502923 -0.42776828]
 [ 0.04442304  0.05551589 -0.74758269  1.2105345 ]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.48377825  0.         -0.36476771  0.04442465]
 [ 0.53934114  1.         -0.0701061  -0.24588141]
 [-0.24464957  0.          1.24526516 -0.57332848]
 [-0.77846982  0.          0.18960864  1.77478525]]
Найдено пиков: 596
  Итерация 1: max Δ = 0.626332
  Итерация 2: max Δ = 0.017070
  Итерация 3: max Δ = 0.009219
  Итерация 6: max Δ = 0.000000
  Сходимость на итерации 6
   matrix2:
[[0.35266548 0.18452131 0.02708981 0.04086919]
 [0.27847287 0.40512604 0.1724

🔄 Обработка SRD:  78%|████████████████████████▊       | 31/40 [00:19<00:03,  2.46файл/s, file=7_pGEM_3_E4_PDMA6_36...]

   matrixdef:
[[1.         0.45604774 0.0386066  0.00233519]
 [0.7911185  1.         0.33528826 0.00992312]
 [0.4836292  0.64456743 1.         0.2899912 ]
 [0.23337233 0.3416751  0.61324358 1.        ]]
   matrix inv:
[[ 1.57147065 -0.8695187   0.27710918 -0.07540056]
 [-1.25656518  1.98030658 -0.73611832  0.19675133]
 [ 0.03865243 -0.87397045  1.56450002 -0.44510899]
 [ 0.03889592  0.06225692 -0.7725759   1.2233316 ]]
   matrix1:
[[ 1.87427466 -0.03312171  0.34479137 -0.26368996]
 [ 0.60630859  1.35361763  0.10741908  0.01640991]
 [-0.41295938 -0.29950287  0.99897355  0.26505202]
 [-1.06762387 -0.02099305 -0.451184    0.98222804]]
Найдено пиков: 591
  Итерация 1: max Δ = 0.617619
  Итерация 2: max Δ = 0.026528
  Итерация 3: max Δ = 0.002830
  Итерация 6: max Δ = 0.000000
  Сходимость на итерации 6
   matrix2:
[[0.38465234 0.19326087 0.05135836 0.03930406]
 [0.27994792 0.37898833 0.16725209 0.05654826]
 [0.194458   0.26360274 0.47926218 0.21674598]
 [0.14094174 0.16414806 0.30212738 0.

🔄 Обработка SRD:  80%|█████████████████████████▌      | 32/40 [00:19<00:03,  2.36файл/s, file=7_pGEM_3_F4_PDMA6_36...]

   matrixdef:
[[1.         0.39606801 0.03340276 0.00383772]
 [0.77547187 1.         0.36994269 0.01808735]
 [0.48255914 0.63146025 1.         0.30181345]
 [0.24261713 0.34556499 0.60610592 1.        ]]
   matrix inv:
[[ 1.44336155e+00 -7.09601192e-01  2.56866438e-01 -7.02301671e-02]
 [-1.11971135e+00  1.86258006e+00 -7.75738299e-01  2.04736265e-01]
 [-6.67499824e-04 -8.46221471e-01  1.59570008e+00 -4.66295289e-01]
 [ 3.71533793e-02  4.14187902e-02 -7.61415473e-01  1.22891369e+00]]
   matrix1:
[[ 0.91237892  0.08608484  0.52645834  0.12307373]
 [-0.06645574  1.32502016 -0.07617564 -0.01233931]
 [-0.27866551 -0.36804241  0.84108068 -0.44642407]
 [ 0.43274233 -0.0430626  -0.29136337  1.33568965]]
Найдено пиков: 592
  Итерация 1: max Δ = 0.623422
  Итерация 2: max Δ = 0.022448
  Итерация 3: max Δ = 0.007411
  Итерация 6: max Δ = 0.020680
  Итерация 11: max Δ = 0.002045
  Сходимость на итерации 14
   matrix2:
[[ 0.26877616 -7.77860883  0.05079289  0.04291224]
 [ 0.33369188 13.53777113  0.1

🔄 Обработка SRD:  82%|██████████████████████████▍     | 33/40 [00:20<00:04,  1.66файл/s, file=7_pGEM_4_G4_PDMA6_36...]

   matrixdef:
[[1.         0.47557381 0.04230873 0.00409582]
 [0.76525521 1.         0.36791083 0.01995347]
 [0.53067046 0.7018981  1.         0.26521352]
 [0.25300136 0.35296363 0.5977819  1.        ]]
   matrix inv:
[[ 1.57349848 -0.95253113  0.32843473 -0.0745438 ]
 [-1.20659907  2.08982508 -0.82695156  0.1825615 ]
 [ 0.00538419 -0.98596269  1.60527071 -0.40608817]
 [ 0.02456975  0.09275008 -0.75081238  1.19717428]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.09280181  0.42067637 -0.31978946]
 [ 0.          1.6220142   0.01751256 -0.36457764]
 [ 0.         -0.21037766  1.41485723 -0.4254744 ]
 [ 0.         -0.50443835 -0.85304616  2.1098415 ]]
Найдено пиков: 598
  Итерация 1: max Δ = 0.620446
  Итерация 2: max Δ = 0.026338
  Итерация 3: max Δ = 0.005518
  Итерация 6: max Δ = 0.000000
  Сходимость на итерации 6
   matrix2:
[[0.36900468 0.18890379 0.05949657 0.02724489]
 [0.26562398 0.37501171 0.1814

🔄 Обработка SRD:  85%|███████████████████████████▏    | 34/40 [00:21<00:03,  1.57файл/s, file=7_pGEM_4_H4_PDMA6_36...]

   matrixdef:
[[1.         0.46961311 0.03902247 0.0040087 ]
 [0.78432614 1.         0.32611135 0.0124356 ]
 [0.48941398 0.65747166 1.         0.32969758]
 [0.24698497 0.35771966 0.59872657 1.        ]]
   matrix inv:
[[ 1.59023522 -0.90276969  0.28587504 -0.0894006 ]
 [-1.26038446  1.99537568 -0.73473564  0.22247937]
 [ 0.0389088  -0.8824487   1.59454179 -0.51489876]
 [ 0.03480436  0.03753093 -0.76247199  1.25077893]]
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.09502317  1.0862409   0.         -0.2353535 ]
 [ 0.51922253  4.7426297   0.          0.17810066]
 [-0.22574228 -2.95585115  1.          0.13315702]
 [-0.38850342 -1.87301944  0.          0.92409582]]
Найдено пиков: 597
  Итерация 1: max Δ = 0.618462
  Итерация 2: max Δ = 0.989971
  Итерация 3: max Δ = 65.452228
  Итерация 6: max Δ = 0.001103
  Сходимость на итерации 7
   matrix2:
[[ 3.55703596e-01  2.90070505e-01 -2.43353783e+01  3.78979467e-02]
 [ 2.6374

🔄 Обработка SRD:  88%|████████████████████████████    | 35/40 [00:21<00:02,  1.88файл/s, file=pGEM_1_B2_PDMA6_36.s...]

   matrixdef:
[[1.00000000e+00 4.12284285e-01 3.26240212e-02 8.62100045e-04]
 [8.54155600e-01 1.00000000e+00 3.05580109e-01 8.67779832e-03]
 [5.17744243e-01 6.43707991e-01 1.00000000e+00 3.55316013e-01]
 [2.65443832e-01 3.59953642e-01 5.96776962e-01 1.00000000e+00]]
   matrix inv:
[[ 1.5498901  -0.75720481  0.22551922 -0.07489588]
 [-1.3372204   1.90294816 -0.67099056  0.22305311]
 [ 0.04249736 -0.83880293  1.58716179 -0.55670167]
 [ 0.04456714  0.01660049 -0.76551878  1.2718186 ]]
   matrix1:
[[ 2.18442623  0.16148964 -0.31433223 -0.35046546]
 [ 0.24180328  1.28929175 -0.28178427  0.14679203]
 [-0.60655738 -0.4947507   1.50512094  0.230503  ]
 [-0.81967213  0.0439693   0.09099556  0.97317042]]
Найдено пиков: 598
  Итерация 1: max Δ = 0.636810
  Итерация 2: max Δ = 0.079607
  Итерация 3: max Δ = 3.025643
  Итерация 6: max Δ = 0.001339
  Сходимость на итерации 7
   matrix2:
[[ 3.27355105e-01  1.01604013e-01 -8.57692308e+00  8.70168468e-03]
 [ 2.76505030e-01  3.06876848e-01 -1.48461538e+

🔄 Обработка SRD:  90%|████████████████████████████▊   | 36/40 [00:22<00:02,  1.99файл/s, file=pGEM_3_E2_PDMA6_36.s...]

   matrixdef:
[[1.         0.42396575 0.04853408 0.00498681]
 [0.78869736 1.         0.37725791 0.0144547 ]
 [0.48470116 0.64324176 1.         0.26119599]
 [0.22598995 0.32876539 0.55776983 1.        ]]
   matrix inv:
[[ 1.50795375 -0.7845357   0.25828278 -0.06364207]
 [-1.20230839  1.9511149  -0.77879458  0.18121092]
 [ 0.03304898 -0.88203764  1.54993854 -0.39225294]
 [ 0.03606127  0.02781212 -0.66683757  1.17359345]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.          0.09036145  0.0701107 ]
 [ 0.          1.          0.20481928  0.28782288]
 [ 0.          0.          0.83855422 -0.16420664]
 [ 0.          0.         -0.13373494  0.80627306]]
Найдено пиков: 564
  Итерация 1: max Δ = 0.654853
  Итерация 2: max Δ = 0.015898
  Итерация 3: max Δ = 0.016732
  Итерация 6: max Δ = 0.001884
  Сходимость на

🔄 Обработка SRD:  92%|█████████████████████████████▌  | 37/40 [00:22<00:01,  2.05файл/s, file=pGEM_3_F2_PDMA6_36.s...]

   matrixdef:
[[1.         0.4381333  0.05257695 0.00441328]
 [0.78055882 1.         0.38989931 0.01373158]
 [0.47315532 0.63341957 1.         0.26354891]
 [0.21796025 0.31790945 0.55320799 1.        ]]
   matrix inv:
[[ 1.52558133 -0.82312951  0.27885541 -0.06892199]
 [-1.20377262  1.98346617 -0.81705803  0.19341121]
 [ 0.03211505 -0.87566725  1.56070698 -0.39944006]
 [ 0.0324083   0.033273   -0.66442451  1.17450844]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.         -0.03703704 -1.66019417  0.        ]
 [ 0.          1.70781893 -0.3592233   0.        ]
 [ 0.          0.11934156  4.60194175  0.        ]
 [ 0.         -0.79012346 -1.58252427  1.        ]]
Найдено пиков: 527
  Итерация 1: max Δ = 0.658997
  Итерация 2: max Δ = 0.028982
  Итерация 3: max Δ = 0.032467
  Итерация 6: max Δ = 0.099825
  Сходимость на

🔄 Обработка SRD:  95%|██████████████████████████████▍ | 38/40 [00:22<00:00,  2.09файл/s, file=pGEM_4_G2_PDMA6_36.s...]

   matrixdef:
[[1.         0.41367722 0.05000864 0.00458785]
 [0.81624645 1.         0.39529222 0.01520487]
 [0.50024062 0.64153248 1.         0.24483733]
 [0.23944218 0.33585784 0.58281732 1.        ]]
   matrix inv:
[[ 1.51607232 -0.77816412  0.26705034 -0.06050752]
 [-1.2522847   1.98904799 -0.82742163  0.17808579]
 [ 0.0360235  -0.89679739  1.5686896  -0.37060336]
 [ 0.03658284  0.04095701 -0.70030654  1.1706706 ]]
Предупреждение: для канала 0 (G) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.          0.1607565  -0.11507937  0.08768971]
 [ 0.          0.94562648 -0.14880952 -0.0623946 ]
 [ 0.         -0.13947991  0.98412698  0.0623946 ]
 [ 0.          0.03309693  0.2797619   0.91231029]]
Найдено пиков: 534
  Итерация 1: max Δ = 0.636632
  Итерация 2: max Δ = 0.017081
  Итерация 3: max Δ = 0.008422
  Итерация 6: max Δ = 0.001524
  Сходимость на итерации 8
   matrix2:
[[0.3332066  0.17760334 0.06696619 0.04146645]
 [0.26479243 0.40389787 0.1711

🔄 Обработка SRD:  98%|███████████████████████████████▏| 39/40 [00:23<00:00,  1.97файл/s, file=pGEM_4_H2_PDMA6_36.s...]

   matrixdef:
[[1.         0.44193712 0.05277209 0.0041219 ]
 [0.7750569  1.         0.39160573 0.01317801]
 [0.48771745 0.65593278 1.         0.25148645]
 [0.2322792  0.33857206 0.57360756 1.        ]]
   matrix inv:
[[ 1.52691042 -0.84034155  0.28719093 -0.06744437]
 [-1.19639401  2.01093008 -0.83200395  0.18766908]
 [ 0.03199465 -0.91972572  1.5794473  -0.38522132]
 [ 0.03204368  0.04191076 -0.69099811  1.17309228]]
Предупреждение: для канала 1 (A) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 2 (T) не найдено чистых пиков. Использован единичный вектор как fallback.
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.10045662  0.          0.          0.        ]
 [ 0.06621005  1.          0.          0.        ]
 [-0.10273973  0.          1.          0.        ]
 [-0.06392694  0.          0.          1.        ]]
Найдено пиков: 545
  Итерация 1: max Δ = 0.638572
  Итера

🔄 Обработка SRD: 100%|████████████████████████████████| 40/40 [00:24<00:00,  1.64файл/s, file=pGEM_4_H2_PDMA6_36.s...]

   matrixdef:
[[1.         0.40660971 0.04700698 0.00482402]
 [0.81167859 1.         0.40013742 0.0151031 ]
 [0.51497883 0.65486789 1.         0.26874182]
 [0.24013181 0.33527166 0.55782586 1.        ]]
   matrix inv:
[[ 1.4960869  -0.76474481  0.27439427 -0.06940835]
 [-1.22279812  1.9861538  -0.85145426  0.20472309]
 [ 0.01963306 -0.91430102  1.59662497 -0.41536583]
 [ 0.03975967  0.02775924 -0.67106101  1.1797311 ]]
Предупреждение: для канала 3 (C) не найдено чистых пиков. Использован единичный вектор как fallback.
   matrix1:
[[ 1.11827957 -0.0576123  -0.01774722  0.        ]
 [ 0.26075269  1.83210733 -0.15049014  0.        ]
 [ 0.0188172  -0.66101899  0.89037529  0.        ]
 [-0.39784946 -0.11347603  0.27786207  1.        ]]
Найдено пиков: 525
  Итерация 1: max Δ = 0.647206
  Итерация 2: max Δ = 0.014774
  Итерация 3: max Δ = 0.011243
  Итерация 6: max Δ = 0.000897
  Сходимость на итерации 7
   matrix2:
[[0.3328091  0.17104585 0.06874238 0.05497331]
 [0.28225309 0.4154683  0.1707